### PR TITLE
Update node affinity to K8s 1.6 spec

### PR DESCRIPTION
**Pull request by eddieesquivel**
I'm proposing an edit to this file that is inline with the K8s 1.6 affinity spec.

### CODE REVIEW

**Comment by kimoonkim** [comment]
@eddieesquivel Thanks for trying out HDFS on K8s and writing this PR for it!

@ash211 is right. This will break 1.5 support. I think in general we want to keep backward compatibility to one version prior. So if the current k8s version is 1.6, then we want to support both 1.6 and 1.5.

But the problem, in this case, is that the node affinity feature itself was alpha in 1.5, which k8s dropped the backward compatibility in 1.6. The minute we use the 1.6 syntax, it doesn't work with 1.5.

Perhaps the best thing we can try is to flag guard 1.6 and 1.5 syntaxes using the [helm chart if/else control](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/control_structures.md), with the default preferring the 1.6 syntax. @eddieesquivel Any chance we can try it out?

**Comment by foxish** [comment]
1.7 is going out sometime next week, so, we could in theory merge this after that and keep the 1 version backward compatibility - the use of if..else in the templating is an option, just requires a bit more maintenance effort.

**Comment by kimoonkim** [comment]
@foxish Tha's a good point. Less work!

**Comment by erikerlandson** [comment]
I second the @foxish proposal to merge after 1.7 lands

**Comment by jpiper** [comment]
Is there any reason why you've chosen to go down the route of tagging the nodes you _don't_ want to be data nodes and then using the `affinity` API? Surely it's simpler to just tag the nodes you _do_ want to be HDFS nodes and then simply use a `nodeSelector`.

**Comment by rporres** [comment]
I do agree with @jpiper. That's particularly relevant in a cluster where you may have different type of k8s workers, some of them holding datanodes and others for different services.

**Comment by kimoonkim** [comment]
@jpiper @rporres Initially the datanode helm chart did not support any blacklist. So datanode daemons launched on every k8s cluster node. We thought this was easier on user's part, as they didn't need to tag any nodes to use the chart.

But it turned out this meant even the k8s master node will launch a datanode. So the blacklist was introduced to exclude the master node.

As to the mechanism, we ended up with `affinity` because the reference [doc](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/) implied that `nodeSelector` will be eventually deprecated by `affinity`, which is a superset of `nodeSelector`. 

>nodeSelector continues to work as usual, but will eventually be deprecated, as node affinity can express everything that nodeSelector can express.

But I think the mechanism is less important than the use cases we want to support. I am curious about your use cases. Do you usually launch datanodes on a subset of k8s cluster nodes? Can you please elaborate on the examples and rationales behind that?

If the use cases are well justified, we can support both whitelist and blacklist as options, IMO. (I have seen other systems doing just that as well, so why not)

**Comment by erikerlandson** [comment]
Per SIG discussion, we should revisit what our intentions are regarding "current-plus-previous" version support for k8s.  If we are committed to this, then preserving 1.5 compatibility is no longer an issue.

**Comment by rporres** [comment]
Hi @kimoonkim We're building an application that will be run in a Spark cluster but needs to keep metadata in a Postgresql instance and we also use RabbitMQ to schedule jobs. We are transitioning to handle of our services in k8s so we have one way of handling applications. We have three kind of k8s workers, each with different hardware specs (we're building the cluster on baremetal servers)

* Spark workers: They will run HDFS data nodes andSpark executors
* Spark metadata: For the moment just one worker with HDFS name node. In the near future we want to add HA using Zookeeper so we will have three workers of this type.
* Service workers: They will run other services our app needs

So it makes sense for us to use explicit tagging as suggested by @jpiper as we have to tag the rest of the nodes otherwise (master and non spark workers)

**Comment by jpiper** [comment]
Ah, I hadn't seen that `nodeSelector` was being deprecated. Makes sense to go with `affinity` then.

I think irrespective of the support model you decide to adopt, the easiest thing is to just put a note/example in the docs describing different deployment methodologies for `affinity` vs. `antiAffinity` - it's trivial to change for anyone that understands how kubernetes works.

**Comment by kimoonkim** [comment]
@rporres Your use case makes sense to me. I see whitelist would support the use case much better. Thanks a lot for detailing the scenario. I'll try incorporating the model in a follow-up change soon. (Perhaps after this change is merged in)

**Comment by kimoonkim** [comment]
I see kubernetes 1.7 is released now. ([news](http://www.zdnet.com/article/kubernetes-1-7-released/)) I don't know how stable 1.7 is right now, but we should be able to drop the 1.5 backward compatibility soon.

@eddieesquivel I'll take another look at this change.

**Comment by foxish** [comment]
We can drop support when 1.7.1 comes out.

**Comment by kimoonkim** [comment]
Kubernetes 1.7.2 is out. So I think we can drop 1.5 support now.

**Comment by kimoonkim** [comment]
Merging in this change soon.

**Pull request merged**
