### PR TITLE
ClusterFirstWithHostNet to replace resolv.conf override

### PR DESCRIPTION
**Pull request by hunter**
A small change to use the `ClusterFirstWithHostNet` dnsPolicy that landed in K8s 1.6 to avoid the override of the resolv.conf. Since it basically does the same thing the `hdfs-resolv-conf` can probably be retired unless K8s 1.5 support is still needed.

### CODE REVIEW

**Comment by kimoonkim** [comment]
Hi @hunter. Welcome to kubernetes-hdfs!

I took a glance at the PR and it looks good to me. This takes care of one of the TODOs. So thanks!

We are about to drop 1.5 support pretty soon. Just waiting for 1.7.1 to come out so we can move on to 1.6 and 1.7 as supported versions. I think I can merge this once that happens. 


Were you able to test this PR? I'm curious how the user experience gets better with this! I think we can even remove the step for creating the config map, but we can make the change after we merge this PR.

**Comment by kimoonkim** [comment]
Oh, I just checked. K8s 1.7.2 is released. ([link](https://github.com/kubernetes/kubernetes/releases/tag/v1.7.2)) So we can merge this! I'll take a final look at this PR soon.

**Comment by hunter** [comment]
I have done some basic testing deploying on GKE (running K8s 1.7.1) and it seemed to work. I haven't run the current configmap chart so can't really compare.

**Comment by kimoonkim** [comment]
> I haven't run the current configmap chart 

This is actually what I wanted to hear. i.e. It works without the configmap chart, which involves some manual steps and thus is difficult to launch. Thanks!

**Comment by kimoonkim** [comment]
Merging in soon.

**Pull request merged**
